name: Sighted Text
description: Using Sighted to convert your input into Markdown bionic text
title: "Sighted: Bionic Text"
body:
  - type: textarea
    attributes:
      label: Text
      description: Write or paste your text here
    validations:
      required: true
  - type: dropdown
      id: type
      attributes:
        label: Method
        description: Set the fixation
        options:
          - Bold
          - Italic
          - Strikethrough
          - Superscript
          - Subscript
        default: 0
  - type: dropdown
    id: fixation
    attributes:
      label: Fixation
      description: Set the fixation
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
      default: 1
  - type: dropdown
    id: saccade
    attributes:
      label: Saccade
      description: Set the saccade
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
      default: 0
